/*
  Warnings:

  - The values [ONE_YEAR_TRAVELER] on the enum `BadgeType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "public"."BadgeType_new" AS ENUM ('REVIEW_BADGE', 'REGION_BADGE', 'SUSTAINABILITY_BADGE', 'SEASONAL_BADGE', 'EXCHANGE_BADGE', 'REFERRAL_BADGE', 'VERIFICATION_BADGE', 'LOYALTY_BADGE', 'EARLY_ADOPTER', 'PREMIUM_TRAVELER', 'TOP_SUPPORTER', 'TRAVELER', 'SUPPORTER', 'GOLDEN_HOST', 'VERIFIED', 'DUO', 'LOTS_OF_FRIENDS', 'PURE_CHARISMA', 'VIP', 'DIAMOND_VIP', 'THE_FIRST_TRADE', 'EXPERIENCED', 'VETERAN', 'PHILOXENIA', 'IT_MY_TOWN', 'EMPIRE', 'EXPLORER', 'AUTUMN_TRAVELER', 'AUTUMN_EXPERT_TRAVELER', 'WINTER_TRAVELER', 'WINTER_EXPERT_TRAVELER', 'SPRING_TRAVELER', 'SPRING_EXPERT_TRAVELER', 'SUMMER_TRAVELER', 'SUMMER_EXPERT_TRAVELER', 'ECO_CONSCIOUS_HOST', 'EVERY_EURO_COUNTS', 'ATTICA', 'ATTICA_EXPERT', 'CENTRAL_GREECE', 'CENTRAL_GREECE_EXPERT', 'SPORADES', 'SPORADES_EXPERT', 'THRACE', 'THRACE_EXPERT', 'IONIAN', 'IONIAN_EXPERT', 'SARONIC', 'SARONIC_EXPERT', 'CRETE', 'CRETE_EXPERT', 'EPIRUS', 'EPIRUS_EXPERT', 'CYCLADES', 'CYCLADES_EXPERT', 'DODECANESE', 'DODECANESE_EXPERT', 'GREECE_TROTTER', 'PELOPONNESE', 'PELOPONNESE_EXPERT', 'NORTH_AEGEAN', 'NORTH_AEGEAN_EXPERT', 'MACEDONIA', 'MACEDONIA_EXPERT');
ALTER TABLE "public"."Badge" ALTER COLUMN "type" TYPE "public"."BadgeType_new" USING ("type"::text::"public"."BadgeType_new");
ALTER TYPE "public"."BadgeType" RENAME TO "BadgeType_old";
ALTER TYPE "public"."BadgeType_new" RENAME TO "BadgeType";
DROP TYPE "public"."BadgeType_old";
COMMIT;
